name: test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.2.0
  http: ^1.1.0
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  country_picker: ^2.0.20
  shared_preferences: ^2.2.0
  firebase_auth: ^4.10.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


