// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktawp7X4zUE9K52yCDBSrqZLN5wf2FKU',
    appId: '1:603248941877:web:088fef0e907dd165088a7c',
    messagingSenderId: '603248941877',
    projectId: 'muslim-marraige-online',
    authDomain: 'muslim-marraige-online.firebaseapp.com',
    storageBucket: 'muslim-marraige-online.appspot.com',
    measurementId: 'G-NLTNJPKT3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIP0nJuC2XNohlvNKq_Jliy6c8djRSMQ',
    appId: '1:862979522815:android:f789e0f4bc784ce9cd4cca',
    messagingSenderId: '603248941877',
    projectId: 'muslimmatt-270d5',
    storageBucket: 'muslimmatt-270d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFIP0nJuC2XNohlvNKq_Jliy6c8djRSMQ',
    appId: '1:862979522815:ios:f789e0f4bc784ce9cd4cca',
    messagingSenderId: '603248941877',
    projectId: 'muslimmatt-270d5',
    storageBucket: 'muslimmatt-270d5.appspot.com',
    iosClientId: '603248941877-kna3fsu407ta54cqgh0baho11n6dntgb.apps.googleusercontent.com',
    iosBundleId: 'com.muslimmarraige.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9jRR4kF6gn4dLgxHXc2IS-6bvxCqEFg',
    appId: '1:603248941877:ios:729fa8a9f749a006088a7c',
    messagingSenderId: '603248941877',
    projectId: 'muslim-marraige-online',
    storageBucket: 'muslim-marraige-online.appspot.com',
    iosClientId: '603248941877-kna3fsu407ta54cqgh0baho11n6dntgb.apps.googleusercontent.com',
    iosBundleId: 'com.muslimmarraige.online',
  );
}
